#!/bin/bash

set -euxo pipefail

# TODO: uncomment and keep only the checks that apply to this repository

# npx tsc --noEmit
# yarn lint
# yarn test
# yarn test:all

# bundle exec rubocop
# bundle exec rspec
# bundle exec brakeman --run-all-checks --exit-on-warn --exit-on-error --rails8 --no-pager --quiet
# bundle exec rails_best_practices . -c config/rails_best_practices.yml
