#!/usr/bin/env ruby

if `[ -d 'spec' ] && git diff --cached spec | grep -e '^+'` =~ /,\s?(:focus|focus:\s?true|:focus\s?=>\s?true)/
  puts "\e[31mPlease focus and remove your :focus flags before committing :)\n\n"
  exit 1
end
