# https://github.com/Homebrew/homebrew-bundle
# Usage: `brew bundle`

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/cask'
tap 'heroku/brew'

cask_args appdir: '/Applications'

brew 'awscli'
brew 'ccat'
brew 'colordiff'
brew 'ctags'
brew 'curl'
brew 'ffmpeg', args: %w[with-freetype with-libass]
brew 'ghostscript'
brew 'git'
brew 'gpg'
brew 'heroku'
brew 'highlight'
brew 'imagemagick'
brew 'macvim'
brew 'mysql'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'redis'
brew 'rsync'
brew 's3cmd'
brew 'the_silver_searcher'
brew 'tree'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask 'chromedriver'
cask 'docker'
cask 'insomnia' # https://insomnia.rest/
cask 'keybase' # https://keybase.io/
cask 'postico'
cask 'sequel-pro'

# ┌───────────────┐
# │ Mac App Store │
# └───────────────┘

mas 'Tweetbot 2 for Twitter', id: 557168941
# mas '1Password 6' # This version is no longer on MAS :(
mas 'Amphetamine', id: 937984704
mas 'DaisyDisk', id: 411643860
mas 'Droplr', id: 498672703
mas 'Evernote', id: 406056744
# mas 'ForkLift', id: 412448059
mas 'Gemini 2', id: 1090488118
mas 'PhotoMill', id: 778590574
mas 'Skitch', id: 425955336
mas 'Slack', id: 803453959
mas 'Telegram Desktop', id: 946399090
# mas 'Wallpaper Wizard 2', id: 1266674560
mas 'WhatsApp Desktop', id: 1147396723
mas 'Xcode', id: 497799835
mas 'The Unarchiver', id: 425424353
# mas 'Super Eraser Pro', id: 1192683670
